### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by arianaa30** [Monaco12138/SR_Tensorflow#1]
Interesting work. When I try to run the app it doesn't show anything on the camera. Should I see anything? 
I select Yolo and I thought it should show me the object detection results.

**Comment by Monaco12138** [comment]
Hi! This app is currently designed for super-resolution tasks, with only the default QuicSR model available. I read the camera input at a resolution of 960x540 and upscale it by two times to 1920x1080. Therefore, the camera feed you see as output is already enhanced by the super-resolution model.

**Comment by arianaa30** [comment]
Hi @Monaco12138 
I noticed QuickSR has multiple sizes [here](https://github.com/quic/aimet-model-zoo/tree/develop/aimet_zoo_torch/quicksrnet/model/model_cards) (small, medium, large). Which size is `quicsr_float32_epoch_200.tflite`?

**Comment by Monaco12138** [comment]
We use this [quicksrnet_small_2x_w8a8](https://github.com/quic/aimet-model-zoo/blob/develop/aimet_zoo_torch/quicksrnet/model/model_cards/quicksrnet_small_2x_w8a8.json)
